/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface RhapSideDrawer {
        "htitle": string;
        "open": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRhapSideDrawerElement extends Components.RhapSideDrawer, HTMLStencilElement {
    }
    var HTMLRhapSideDrawerElement: {
        prototype: HTMLRhapSideDrawerElement;
        new (): HTMLRhapSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "rhap-side-drawer": HTMLRhapSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface RhapSideDrawer {
        "htitle"?: string;
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "rhap-side-drawer": RhapSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "rhap-side-drawer": LocalJSX.RhapSideDrawer & JSXBase.HTMLAttributes<HTMLRhapSideDrawerElement>;
        }
    }
}
